version: '3.8'

services:
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=Europe/Moscow
    ports:
      - 5436:5432

  app:
    build: ./
    command: ./wait-for-postgres.sh db ./.bin/neurohacking-api
    ports:
      - 8001:8000
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - GIN_MODE=release
      - SOLT=${SOLT}
      - SIGNATURE_KEY=${SIGNATURE_KEY}

